name: S3 CI/CD

on:
  push:
    branches: [ jho2301 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: S3 Sync
        run: aws s3 sync . s3://apple-clone-jho2301 --region "ap-northeast-2"
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECURE_ACCESS_KEY }}

